version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    deploy:
      placement:
        constraints: 
          - node.role == manager
      restart_policy:
        condition: on-failure

  web:
    image: ${DOCKER_IMAGE_REPO}:${DOCKER_IMAGE_TAG:-latest}
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: postgrespw
      DJANGO_DB_NAME: postgres
    networks:
      - app_network
    ports:
      - "80:8000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  app_network:
    driver: overlay
